add a basic docker test

diff --git a/.github/workflows/run-build-images.yaml b/.github/workflows/run-build-images.yaml
--- a/.github/workflows/run-build-images.yaml
+++ b/.github/workflows/run-build-images.yaml
@@ -11,8 +11,37 @@ jobs:
     uses: ./.github/workflows/define-build-linux-image.yaml
     secrets: inherit
 
-  push:
+  test-linux:
     needs: [build-linux]
+    runs-on: [self-hosted, linux]
+    steps:
+    - name: lowercase github.repository
+      run: |
+        echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
+    - name: Download cached docker image
+      run: |
+        curl -X GET http://192.168.0.11:25000/attachments/gha-runner/1/image_ubuntu.tar -o /tmp/image_ubuntu.tar
+    - name: Load image
+      run: |
+        docker load --input /tmp/image_ubuntu.tar
+    - name: Run container with tests
+      run: |
+        docker run --name gha-runner --runtime sysbox-runc -e TEST_ONLY_RUN=yes -e REPO=Ableytner/docker-github-actions-runner -e TOKEN=XXXX ${{ env.IMAGE_NAME }}:latest
+        if [[ $? -ne 0 ]]; then
+          echo "tests failed!"
+          exit 1
+        fi
+    - name: Print out server container logs
+      if: failure()
+      run: |
+        docker logs ${{ env.CONTAINER_ID }}
+    - name: Stop and delete server container
+      if: always()
+      run: |
+        docker rm -f ${{ env.CONTAINER_ID }}
+
+  push:
+    needs: [test-linux]
     runs-on: [self-hosted, linux]
     permissions:
       contents: read
